name: LUS4covid
channels:
  - conda-forge
  - apple
dependencies:
  - gudhi=3.7.0
  - ipykernel=6.15.3
  - jupyter=1.0.0
  - notebook=6.4.11
  - pandas=1.4.2
  - pip=22.2.2
  - plotly=5.10.0
  - progressbar2=4.0.0
  - python=3.8.13
  - scikit-image=0.19.3
  - seaborn=0.11.2
  - statannot=0.2.3
  - tensorflow-deps=2.8.0
  - tqdm=4.64.1
  - openpyxl
  - pip:
    - giotto-tda==0.6.0
    - keras==2.8.0
    - scikit-learn==1.1.0
    - scikit-tda==1.0.0
    - scikit-video==1.1.11
    - scipy==1.8.0
    - tensorflow-macos==2.8.0
    - tensorflow-metal==0.4.0
    - xgboost==1.7.2