name: DL4LUS
channels:
  - conda-forge
dependencies:
  - jupyter
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - pandas=1.4.2
  - pip=22.2.2
  - plotly=5.10.0
  - progressbar2=4.0.0
  - python=3.8.13
  - scikit-image=0.19.3
  - seaborn=0.11.2
  - statannot=0.2.3
  - tqdm=4.64.1
  - openpyxl
  - pip:
    - giotto-tda==0.6.0
    - keras==2.8.0
    - scikit-learn==1.1.0
    - scikit-tda==1.0.0
    - scikit-video==1.1.11
    - scipy==1.8.0
    - opencv-python==4.7.0.72